version: '3.7'
services:
  node-app:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: .
    command: bash -c "npm start"
    # Mapping of container port to host
    ports:
      - "5121:3000"

  mysql-8-0-19:
    container_name: mysql-8-0-19
    image: mysql:8.0.19
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - ./volumes-mysql/mysql-8-0-19:/var/lib/mysql
    ports:
      - "3306:3306"
